# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: FilmSoc
email: ussu.film@surrey.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  At Film Society, we aim to show a mixture of classics that everyone knows, and to introduce people to new films to enjoy! Screenings take place on campus twice a week, and attendance and membership are completely free.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://surreyfilmsoc.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: surreyfilmsoc
instagram_username: surreyfilmsoc

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts
  - package.json
  - webpack.config.js
  - yarn.lock

collections:
  screenings:
    output: true
    permalink: /:collection/:name/

feed:
  collections:
    screenings:
      path: "/screenings.xml"

timezone: Etc/UTC
future: true